import type { Exercise } from "./types";

export const SEED_EXERCISES: Exercise[] = [
  // ============== CHEST ==============
  {
    id: "ex_bench",
    name: "Barbell Bench Press",
    category: "Chest",
    equipment: "Barbell",
    primaryMuscles: [
      "Pectoralis Major - Sternocostal Part",
      "Pectoralis Major - Clavicular Part",
    ],
    secondaryMuscles: [
      "Deltoid - Clavicular Part",
      "Triceps Brachii Lateral",
      "Triceps Brachii Longus",
      "Serratus Anterior",
    ],
    preparation:
      "Lie supine on a flat bench. Grip the bar slightly wider than shoulder width. Plant feet, retract scapulae.",
    execution:
      "Unrack and lower the bar with control to mid chest, then press it back over the shoulders until arms are extended.",
    tip: "Keep wrists stacked over elbows and elbows tucked roughly 60-75 degrees from torso.",
  },
  {
    id: "ex_inc_bb",
    name: "Incline Bench Press (Barbell)",
    category: "Chest",
    equipment: "Barbell",
    primaryMuscles: [
      "Pectoralis Major - Clavicular Part",
      "Pectoralis Major - Sternocostal Part",
    ],
    secondaryMuscles: [
      "Deltoid - Clavicular Part",
      "Triceps Brachii Lateral",
      "Triceps Brachii Longus",
    ],
    preparation:
      "Lie supine on incline bench. Dismount barbell from rack over upper chest using wide overhand grip.",
    execution:
      "Lower weight to upper chest. Press bar until arms are extended. Repeat.",
    tip: "Range of motion will be compromised if grip is too wide.",
  },
  {
    id: "ex_inc_db",
    name: "Incline Dumbbell Press",
    category: "Chest",
    equipment: "Dumbbells",
    primaryMuscles: ["Pectoralis Major - Clavicular Part"],
    secondaryMuscles: [
      "Deltoid - Clavicular Part",
      "Triceps Brachii Lateral",
      "Triceps Brachii Longus",
    ],
    preparation:
      "Set bench to 30-45 degrees. Sit, kick dumbbells up to shoulder height.",
    execution:
      "Press dumbbells up and slightly toward each other. Lower with control to chest level.",
    tip: "Your #1 priority chest lift. Bench at moderate incline — too steep shifts work to front delts.",
  },
  {
    id: "ex_dec_bench",
    name: "Decline Bench Press",
    category: "Chest",
    equipment: "Barbell",
    primaryMuscles: ["Pectoralis Major - Sternocostal Part"],
    secondaryMuscles: ["Triceps Brachii Lateral", "Triceps Brachii Longus"],
    preparation: "Lie on decline bench, hook feet, grip barbell shoulder width.",
    execution: "Lower bar to lower chest. Press straight up to lockout.",
    tip: "Use a spotter for safety since unracking on a decline is awkward.",
  },
  {
    id: "ex_db_bench",
    name: "Flat Dumbbell Press",
    category: "Chest",
    equipment: "Dumbbells",
    primaryMuscles: ["Pectoralis Major - Sternocostal Part"],
    secondaryMuscles: [
      "Pectoralis Major - Clavicular Part",
      "Deltoid - Clavicular Part",
      "Triceps Brachii Lateral",
    ],
    preparation: "Lie flat. Kick dumbbells to start position with elbows over wrists.",
    execution: "Press up over shoulders, squeeze, then lower under control.",
    tip: "Greater range of motion than barbell. Watch the descent.",
  },
  {
    id: "ex_db_fly",
    name: "Dumbbell Fly",
    category: "Chest",
    equipment: "Dumbbells",
    primaryMuscles: ["Pectoralis Major - Sternocostal Part"],
    secondaryMuscles: ["Deltoid - Clavicular Part", "Biceps Brachii - Short Head"],
    preparation: "Lie on a flat bench, dumbbells over chest with a soft elbow bend.",
    execution: "Lower dumbbells out in an arc until you feel a chest stretch, then squeeze back together.",
    tip: "Maintain the same elbow angle through the entire rep.",
  },
  {
    id: "ex_cable_fly",
    name: "Cable Fly",
    category: "Chest",
    equipment: "Cable",
    primaryMuscles: ["Pectoralis Major - Sternocostal Part"],
    secondaryMuscles: ["Pectoralis Major - Clavicular Part", "Deltoid - Clavicular Part"],
    preparation: "Set cables at shoulder height, grab handles with split stance.",
    execution: "Bring handles together in front of your chest, squeeze, then control back to a stretched position.",
    tip: "Adjust pulley height to bias upper, mid, or lower chest fibers.",
  },
  {
    id: "ex_pec_deck",
    name: "Pec Deck Machine",
    category: "Chest",
    equipment: "Machine",
    primaryMuscles: ["Pectoralis Major - Sternocostal Part"],
    secondaryMuscles: ["Deltoid - Clavicular Part"],
    preparation: "Sit upright, adjust pads to shoulder height, grasp handles.",
    execution: "Squeeze pads together until they almost touch. Slow eccentric.",
    tip: "Great isolation lift. Avoid shrugging shoulders.",
  },
  {
    id: "ex_pushup",
    name: "Push Up",
    category: "Chest",
    equipment: "Bodyweight",
    primaryMuscles: ["Pectoralis Major - Sternocostal Part"],
    secondaryMuscles: [
      "Deltoid - Clavicular Part",
      "Triceps Brachii Lateral",
      "Serratus Anterior",
      "Rectus Abdominis",
    ],
    preparation: "Hands shoulder width, body in a straight line, core braced.",
    execution: "Lower until chest nearly touches floor. Press back up to lockout.",
    tip: "Elevate feet for harder, hands for easier.",
  },
  {
    id: "ex_dips_chest",
    name: "Chest Dip",
    category: "Chest",
    equipment: "Bodyweight",
    primaryMuscles: ["Pectoralis Major - Sternocostal Part"],
    secondaryMuscles: ["Triceps Brachii Lateral", "Deltoid - Clavicular Part"],
    preparation: "Mount parallel bars, lean torso forward 30 degrees.",
    execution: "Lower until shoulders are below elbows, then press back to lockout.",
    tip: "Lean forward to bias chest. Stay upright to bias triceps.",
  },
  {
    id: "ex_machine_press",
    name: "Machine Chest Press",
    category: "Chest",
    equipment: "Machine",
    primaryMuscles: ["Pectoralis Major - Sternocostal Part"],
    secondaryMuscles: ["Deltoid - Clavicular Part", "Triceps Brachii Lateral"],
    preparation: "Adjust seat so handles align with mid chest.",
    execution: "Press handles forward to full extension, then return slowly.",
    tip: "Useful for high-volume work without spotter risk.",
  },
  {
    id: "ex_svend",
    name: "Svend Press",
    category: "Chest",
    equipment: "Plate",
    primaryMuscles: ["Pectoralis Major - Clavicular Part"],
    secondaryMuscles: ["Deltoid - Clavicular Part", "Triceps Brachii Lateral"],
    preparation: "Hold a plate with both hands at chest, palms pressed inward.",
    execution: "Press the plate straight out, squeezing the inner chest. Pull back.",
    tip: "Constant inward pressure is the whole point.",
  },

  // ============== BACK ==============
  {
    id: "ex_pullup",
    name: "Pull Up",
    category: "Back",
    equipment: "Bodyweight",
    primaryMuscles: ["Latissimus Dorsi", "Teres Major"],
    secondaryMuscles: [
      "Biceps Brachii - Long Head",
      "Biceps Brachii - Short Head",
      "Brachialis",
      "Trapezius - Lower Fibers",
      "Rhomboid Major",
    ],
    preparation: "Hang from bar with overhand grip slightly wider than shoulders.",
    execution: "Pull chest toward bar. Lower with full control to dead hang.",
    tip: "Drive elbows down and back, not just up.",
  },
  {
    id: "ex_chinup",
    name: "Chin Up",
    category: "Back",
    equipment: "Bodyweight",
    primaryMuscles: ["Latissimus Dorsi", "Biceps Brachii - Long Head"],
    secondaryMuscles: ["Brachialis", "Teres Major", "Rhomboid Major"],
    preparation: "Hang with underhand grip, shoulder-width.",
    execution: "Pull chin over bar. Lower under control.",
    tip: "Easier on the shoulder than pull ups for most lifters.",
  },
  {
    id: "ex_deadlift",
    name: "Conventional Deadlift",
    category: "Back",
    equipment: "Barbell",
    primaryMuscles: [
      "Erector Spinae",
      "Gluteus Maximus",
      "Biceps Femoris",
    ],
    secondaryMuscles: [
      "Latissimus Dorsi",
      "Trapezius - Middle Fibers",
      "Trapezius - Upper Fibers",
      "Forearm Flexors",
      "Quadriceps",
    ],
    preparation:
      "Bar over mid foot. Hinge, grip just outside knees. Chest up, lats engaged.",
    execution:
      "Drive floor away. Once bar passes knees, lock hips. Reverse the path.",
    tip: "Bar stays in contact with the legs the whole way up.",
  },
  {
    id: "ex_bb_row",
    name: "Bent-Over Barbell Row",
    category: "Back",
    equipment: "Barbell",
    primaryMuscles: [
      "Latissimus Dorsi",
      "Rhomboid Major",
      "Trapezius - Middle Fibers",
    ],
    secondaryMuscles: [
      "Posterior Deltoid",
      "Biceps Brachii - Long Head",
      "Erector Spinae",
    ],
    preparation: "Hinge at hips to a 45-degree torso angle. Overhand grip outside knees.",
    execution: "Row bar to lower ribs, squeeze shoulder blades, lower with control.",
    tip: "Keep neck neutral. Avoid jerking with the lower back.",
  },
  {
    id: "ex_pendlay",
    name: "Pendlay Row",
    category: "Back",
    equipment: "Barbell",
    primaryMuscles: ["Latissimus Dorsi", "Rhomboid Major"],
    secondaryMuscles: [
      "Trapezius - Middle Fibers",
      "Posterior Deltoid",
      "Biceps Brachii - Long Head",
    ],
    preparation: "Torso parallel to floor, bar on the floor each rep.",
    execution: "Explosively row bar to lower chest, then place it back down.",
    tip: "Reset every rep. No bouncing.",
  },
  {
    id: "ex_lat_pull",
    name: "Lat Pulldown",
    category: "Back",
    equipment: "Cable",
    primaryMuscles: ["Latissimus Dorsi", "Teres Major"],
    secondaryMuscles: [
      "Biceps Brachii - Long Head",
      "Brachialis",
      "Rhomboid Major",
      "Trapezius - Lower Fibers",
    ],
    preparation: "Sit, secure thighs under pad, grip bar slightly wider than shoulders.",
    execution: "Pull bar to upper chest. Slow eccentric back to full stretch.",
    tip: "Wide grip first, immediately superset with reverse grip — same weight, no rest.",
  },
  {
    id: "ex_seated_row",
    name: "Seated Cable Row",
    category: "Back",
    equipment: "Cable",
    primaryMuscles: [
      "Latissimus Dorsi",
      "Rhomboid Major",
      "Trapezius - Middle Fibers",
    ],
    secondaryMuscles: ["Posterior Deltoid", "Biceps Brachii - Long Head"],
    preparation: "Sit tall, knees soft, grip handle.",
    execution: "Pull handle to lower abs while squeezing shoulder blades together.",
    tip: "MAG grip is the game changer. Keep upright, don't rock.",
  },
  {
    id: "ex_db_row",
    name: "One-Arm Dumbbell Row",
    category: "Back",
    equipment: "Dumbbell",
    primaryMuscles: ["Latissimus Dorsi", "Rhomboid Major"],
    secondaryMuscles: [
      "Trapezius - Middle Fibers",
      "Biceps Brachii - Long Head",
      "Posterior Deltoid",
    ],
    preparation: "Brace one knee and hand on bench, hinge flat back.",
    execution: "Row dumbbell to hip, elbow tracks back. Lower fully.",
    tip: "Pause at the top for a stronger squeeze.",
  },
  {
    id: "ex_chest_row",
    name: "Chest-Supported Row",
    category: "Back",
    equipment: "Machine",
    primaryMuscles: ["Rhomboid Major", "Trapezius - Middle Fibers"],
    secondaryMuscles: ["Latissimus Dorsi", "Posterior Deltoid"],
    preparation: "Lie chest down on incline bench with dumbbells hanging.",
    execution: "Row weights up to ribs, squeeze, lower fully.",
    tip: "Removes lower back fatigue from the equation.",
  },
  {
    id: "ex_face_pull",
    name: "Face Pull",
    category: "Back",
    equipment: "Cable",
    primaryMuscles: [
      "Posterior Deltoid",
      "Trapezius - Middle Fibers",
      "Rhomboid Major",
    ],
    secondaryMuscles: ["Trapezius - Upper Fibers", "Infraspinatus"],
    preparation: "Set rope at upper chest height, step back, neutral grip.",
    execution: "Pull rope to forehead, externally rotating so palms face up.",
    tip: "Cue is 'apart and back', not just back.",
  },
  {
    id: "ex_shrug",
    name: "Barbell Shrug",
    category: "Back",
    equipment: "Barbell",
    primaryMuscles: ["Trapezius - Upper Fibers"],
    secondaryMuscles: ["Levator Scapulae", "Forearm Flexors"],
    preparation: "Stand tall, hold barbell in front of thighs.",
    execution: "Shrug shoulders straight up to ears. Hold one beat. Lower.",
    tip: "Don't roll the shoulders. Straight up and down.",
  },
  {
    id: "ex_back_ext",
    name: "Back Extension",
    category: "Back",
    equipment: "Bodyweight",
    primaryMuscles: ["Erector Spinae"],
    secondaryMuscles: ["Gluteus Maximus", "Biceps Femoris"],
    preparation: "Lock feet on hyperextension bench, hips on the pad.",
    execution: "Hinge down with neutral spine, then extend back to a straight line.",
    tip: "Add a plate hugged to the chest as you progress.",
  },

  // ============== LEGS ==============
  {
    id: "ex_squat",
    name: "Back Squat",
    category: "Legs",
    equipment: "Barbell",
    primaryMuscles: ["Quadriceps", "Gluteus Maximus"],
    secondaryMuscles: [
      "Biceps Femoris",
      "Erector Spinae",
      "Adductor Magnus",
      "Soleus",
    ],
    preparation:
      "Bar across upper traps. Feet shoulder width, toes slightly out.",
    execution:
      "Brace, sit back and down to at least parallel. Drive up through mid foot.",
    tip: "Knee sleeves help if you have any knee history. Warm up thoroughly before working sets.",
  },
  {
    id: "ex_front_squat",
    name: "Front Squat",
    category: "Legs",
    equipment: "Barbell",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: [
      "Gluteus Maximus",
      "Erector Spinae",
      "Rectus Abdominis",
      "Adductor Magnus",
    ],
    preparation: "Bar across front delts, elbows high.",
    execution: "Squat down keeping torso vertical, drive up.",
    tip: "If wrist mobility is limited, use a cross-arm grip.",
  },
  {
    id: "ex_goblet",
    name: "Goblet Squat",
    category: "Legs",
    equipment: "Dumbbell",
    primaryMuscles: ["Quadriceps", "Gluteus Maximus"],
    secondaryMuscles: ["Adductor Magnus", "Erector Spinae"],
    preparation: "Hold a single dumbbell at chest, elbows tucked.",
    execution: "Squat between heels, keep chest tall, drive up.",
    tip: "Great teaching squat for beginners.",
  },
  {
    id: "ex_leg_press",
    name: "Leg Press",
    category: "Legs",
    equipment: "Machine",
    primaryMuscles: ["Quadriceps", "Gluteus Maximus"],
    secondaryMuscles: ["Biceps Femoris", "Adductor Magnus"],
    preparation: "Sit, feet shoulder width on platform.",
    execution: "Lower platform until knees reach 90 degrees, press back up.",
    tip: "Don't lock knees out hard at the top.",
  },
  {
    id: "ex_hack_squat",
    name: "Hack Squat",
    category: "Legs",
    equipment: "Machine",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Gluteus Maximus", "Adductor Magnus"],
    preparation: "Shoulders under pads, feet on platform.",
    execution: "Squat down to depth, drive up without locking out.",
    tip: "Higher foot placement biases glutes; lower bias quads.",
  },
  {
    id: "ex_rdl",
    name: "Romanian Deadlift",
    category: "Legs",
    equipment: "Barbell",
    primaryMuscles: ["Biceps Femoris", "Gluteus Maximus"],
    secondaryMuscles: ["Erector Spinae", "Adductor Magnus"],
    preparation: "Stand tall holding bar at hips. Soft knee bend.",
    execution: "Hinge hips back, lower bar along thighs to mid shin. Drive hips through.",
    tip: "Bar tracks along the legs. No rounding.",
  },
  {
    id: "ex_bulgarian",
    name: "Bulgarian Split Squat",
    category: "Legs",
    equipment: "Dumbbells",
    primaryMuscles: ["Quadriceps", "Gluteus Maximus"],
    secondaryMuscles: ["Adductor Magnus", "Biceps Femoris"],
    preparation: "Rear foot elevated on bench, front foot 2-3 ft ahead.",
    execution: "Lower until rear knee nearly touches floor. Drive up.",
    tip: "Keep the front foot's heel grounded.",
  },
  {
    id: "ex_leg_ext",
    name: "Leg Extension",
    category: "Legs",
    equipment: "Machine",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: [],
    preparation: "Sit, pad above ankles, knees aligned with machine pivot.",
    execution: "Extend knees to lockout, squeeze quads, lower with control.",
    tip: "Pause at the top for an extra rep's worth of stimulus.",
  },
  {
    id: "ex_leg_curl",
    name: "Lying Leg Curl",
    category: "Legs",
    equipment: "Machine",
    primaryMuscles: ["Biceps Femoris", "Semitendinosus"],
    secondaryMuscles: ["Gastrocnemius"],
    preparation: "Lie face down, pad on heels.",
    execution: "Curl heels toward glutes. Slow eccentric.",
    tip: "Point toes to bias hamstring; flex toes to add calf.",
  },
  {
    id: "ex_seated_curl",
    name: "Seated Leg Curl",
    category: "Legs",
    equipment: "Machine",
    primaryMuscles: ["Biceps Femoris", "Semitendinosus"],
    secondaryMuscles: ["Gastrocnemius"],
    preparation: "Sit, pad over ankles, thigh pad locked down.",
    execution: "Curl heels under, hold, return slowly.",
    tip: "Better hamstring stretch than the lying version.",
  },
  {
    id: "ex_lunges",
    name: "Walking Lunges",
    category: "Legs",
    equipment: "Dumbbells",
    primaryMuscles: ["Quadriceps", "Gluteus Maximus"],
    secondaryMuscles: ["Biceps Femoris", "Adductor Magnus"],
    preparation: "Hold dumbbells at sides, stand tall.",
    execution: "Step forward, drop rear knee toward floor, drive through front heel to next step.",
    tip: "Chest up the entire walk.",
  },
  {
    id: "ex_calf",
    name: "Standing Calf Raise",
    category: "Legs",
    equipment: "Machine",
    primaryMuscles: ["Gastrocnemius"],
    secondaryMuscles: ["Soleus"],
    preparation: "Shoulders under pads, balls of feet on platform.",
    execution: "Rise as high as possible, hold, drop into a deep stretch.",
    tip: "Full range of motion beats heavy partials.",
  },
  {
    id: "ex_seated_calf",
    name: "Seated Calf Raise",
    category: "Legs",
    equipment: "Machine",
    primaryMuscles: ["Soleus"],
    secondaryMuscles: ["Gastrocnemius"],
    preparation: "Sit with thighs under pads, balls of feet on platform.",
    execution: "Drive up onto toes, squeeze, lower into deep stretch.",
    tip: "Targets the soleus more than standing variations.",
  },
  {
    id: "ex_hip_abductor",
    name: "Hip Abductor",
    category: "Legs",
    equipment: "Machine",
    primaryMuscles: ["Gluteus Medius", "Gluteus Minimus"],
    secondaryMuscles: ["Tensor Fasciae Latae", "Gluteus Maximus"],
    preparation: "Sit upright, knees bent, outer thighs against the pads.",
    execution: "Press knees outward against pads, hold, return slowly.",
    tip: "Non-negotiable finisher every single session, regardless of muscle group. Burn it out.",
  },

  // ============== ARMS ==============
  {
    id: "ex_bb_curl",
    name: "Barbell Curl",
    category: "Arms",
    equipment: "Barbell",
    primaryMuscles: ["Biceps Brachii - Long Head", "Biceps Brachii - Short Head"],
    secondaryMuscles: ["Brachialis", "Brachioradialis", "Forearm Flexors"],
    preparation: "Stand tall, shoulder-width underhand grip, elbows pinned.",
    execution: "Curl bar to chest height, squeeze, lower under control.",
    tip: "Don't swing. Elbows stay glued to your sides.",
  },
  {
    id: "ex_db_curl",
    name: "Dumbbell Curl",
    category: "Arms",
    equipment: "Dumbbells",
    primaryMuscles: ["Biceps Brachii - Long Head", "Biceps Brachii - Short Head"],
    secondaryMuscles: ["Brachialis", "Brachioradialis"],
    preparation: "Stand or sit, dumbbells at sides, palms facing in.",
    execution: "Curl one or both dumbbells, supinating wrist as you rise.",
    tip: "Alternating arms allows heavier loads with less swing.",
  },
  {
    id: "ex_hammer",
    name: "Hammer Curl",
    category: "Arms",
    equipment: "Dumbbells",
    primaryMuscles: ["Brachialis", "Brachioradialis"],
    secondaryMuscles: ["Biceps Brachii - Long Head"],
    preparation: "Stand, neutral grip, dumbbells at sides.",
    execution: "Curl with neutral wrist all the way up. Squeeze and lower.",
    tip: "Hammer curls grow the brachialis and add visible width.",
  },
  {
    id: "ex_preacher",
    name: "Preacher Curl",
    category: "Arms",
    equipment: "Barbell",
    primaryMuscles: ["Biceps Brachii - Short Head"],
    secondaryMuscles: ["Brachialis", "Brachioradialis"],
    preparation: "Sit at preacher bench, upper arms on pad, EZ-bar in hand.",
    execution: "Curl up to forehead, lower fully without locking elbows hard.",
    tip: "Stop just shy of full extension to keep tension.",
  },
  {
    id: "ex_incline_curl",
    name: "Incline Dumbbell Curl",
    category: "Arms",
    equipment: "Dumbbells",
    primaryMuscles: ["Biceps Brachii - Long Head"],
    secondaryMuscles: ["Brachialis"],
    preparation: "Sit on incline bench at 45-60 degrees, arms hanging.",
    execution: "Curl up while keeping elbows behind your torso.",
    tip: "Stretch position emphasizes the long head of the biceps.",
  },
  {
    id: "ex_concentration",
    name: "Concentration Curl",
    category: "Arms",
    equipment: "Dumbbell",
    primaryMuscles: ["Biceps Brachii - Short Head"],
    secondaryMuscles: ["Brachialis"],
    preparation: "Sit on bench, elbow braced against inner thigh.",
    execution: "Curl dumbbell to shoulder, peak contraction at the top.",
    tip: "Single arm focus drives a strong mind-muscle connection.",
  },
  {
    id: "ex_tri_pushdown",
    name: "Triceps Pushdown",
    category: "Arms",
    equipment: "Cable",
    primaryMuscles: ["Triceps Brachii Lateral", "Triceps Brachii Medial"],
    secondaryMuscles: ["Triceps Brachii Longus"],
    preparation: "Stand at cable, grab bar overhand, elbows pinned to sides.",
    execution: "Press bar down to lockout. Slow return to a 90-degree elbow.",
    tip: "Keep upper arms still. Movement is at the elbow only.",
  },
  {
    id: "ex_rope_pushdown",
    name: "Rope Tricep Pushdown",
    category: "Arms",
    equipment: "Cable",
    primaryMuscles: ["Triceps Brachii Lateral", "Triceps Brachii Medial"],
    secondaryMuscles: ["Triceps Brachii Longus"],
    preparation: "Cable rope, neutral grip, elbows tucked.",
    execution: "Press down and rotate hands outward at the bottom.",
    tip: "Split the rope at the bottom for full triceps activation.",
  },
  {
    id: "ex_skull",
    name: "Skull Crusher",
    category: "Arms",
    equipment: "Barbell",
    primaryMuscles: ["Triceps Brachii Longus"],
    secondaryMuscles: ["Triceps Brachii Lateral", "Triceps Brachii Medial"],
    preparation: "Lie flat, EZ bar held with arms vertical.",
    execution: "Lower bar to forehead by bending elbows. Press back up.",
    tip: "Slight angle back of the upper arms targets the long head better.",
  },
  {
    id: "ex_overhead_tri",
    name: "Overhead Triceps Extension",
    category: "Arms",
    equipment: "Dumbbell",
    primaryMuscles: ["Triceps Brachii Longus"],
    secondaryMuscles: ["Triceps Brachii Lateral", "Triceps Brachii Medial"],
    preparation: "Hold a single dumbbell with both hands overhead.",
    execution: "Lower behind the head, squeeze triceps to extend back overhead.",
    tip: "Long head focus. Stretch the bottom hard.",
  },
  {
    id: "ex_dips_tri",
    name: "Triceps Dip",
    category: "Arms",
    equipment: "Bodyweight",
    primaryMuscles: ["Triceps Brachii Lateral", "Triceps Brachii Longus"],
    secondaryMuscles: ["Pectoralis Major - Sternocostal Part", "Deltoid - Clavicular Part"],
    preparation: "Mount parallel bars, body close to vertical.",
    execution: "Lower until elbows hit 90 degrees, press up to lockout.",
    tip: "Stay upright to bias triceps over chest.",
  },
  {
    id: "ex_close_bench",
    name: "Close-Grip Bench Press",
    category: "Arms",
    equipment: "Barbell",
    primaryMuscles: ["Triceps Brachii Lateral", "Triceps Brachii Medial"],
    secondaryMuscles: ["Pectoralis Major - Sternocostal Part", "Deltoid - Clavicular Part"],
    preparation: "Lie on bench, hands shoulder-width on bar.",
    execution: "Lower with elbows tucked, press to lockout.",
    tip: "Don't go narrower than shoulder width or wrists will protest.",
  },
  {
    id: "ex_wrist_curl",
    name: "Wrist Curl",
    category: "Arms",
    equipment: "Dumbbells",
    primaryMuscles: ["Forearm Flexors"],
    secondaryMuscles: [],
    preparation: "Forearms on bench or thighs, palms up, dumbbells in hand.",
    execution: "Let weight roll to fingertips, then curl up by flexing the wrists.",
    tip: "Light weight, high reps. Forearms recover quickly.",
  },

  // ============== SHOULDERS ==============
  {
    id: "ex_ohp",
    name: "Overhead Press (Barbell)",
    category: "Shoulders",
    equipment: "Barbell",
    primaryMuscles: ["Deltoid - Clavicular Part"],
    secondaryMuscles: [
      "Triceps Brachii Lateral",
      "Triceps Brachii Longus",
      "Trapezius - Upper Fibers",
      "Serratus Anterior",
    ],
    preparation: "Bar at front delts, grip just outside shoulders, glutes tight.",
    execution: "Press bar overhead in a straight line. Move head through at lockout.",
    tip: "Squeeze glutes and brace abs to protect lower back.",
  },
  {
    id: "ex_db_press_sh",
    name: "Dumbbell Shoulder Press",
    category: "Shoulders",
    equipment: "Dumbbells",
    primaryMuscles: ["Deltoid - Clavicular Part"],
    secondaryMuscles: ["Triceps Brachii Lateral", "Triceps Brachii Longus", "Serratus Anterior"],
    preparation: "Sit on bench with back support, dumbbells at shoulder height.",
    execution: "Press up to lockout. Lower under control to ear level.",
    tip: "Always build up: 40 -> 45 -> 50 lb. Never start at PR weight.",
  },
  {
    id: "ex_arnold",
    name: "Arnold Press",
    category: "Shoulders",
    equipment: "Dumbbells",
    primaryMuscles: ["Deltoid - Clavicular Part"],
    secondaryMuscles: ["Deltoid - Acromial Part", "Triceps Brachii Lateral"],
    preparation: "Seated, dumbbells at chest with palms facing you.",
    execution: "Rotate palms outward as you press up. Reverse to lower.",
    tip: "The rotation hits front and side delts in one rep.",
  },
  {
    id: "ex_lat_raise",
    name: "Dumbbell Lateral Raise",
    category: "Shoulders",
    equipment: "Dumbbells",
    primaryMuscles: ["Deltoid - Acromial Part"],
    secondaryMuscles: ["Trapezius - Upper Fibers", "Supraspinatus"],
    preparation: "Stand tall, dumbbells at sides with a soft elbow bend.",
    execution: "Raise arms out to shoulder height. Lower under control.",
    tip: "Lead with the elbow, pinky slightly higher than thumb.",
  },
  {
    id: "ex_cable_lat_raise",
    name: "Cable Lateral Raise",
    category: "Shoulders",
    equipment: "Cable",
    primaryMuscles: ["Deltoid - Acromial Part"],
    secondaryMuscles: ["Supraspinatus"],
    preparation: "Stand sideways to cable, low pulley, handle in far hand.",
    execution: "Raise arm out to shoulder height across the body.",
    tip: "Cable keeps tension constant through the full range.",
  },
  {
    id: "ex_front_raise",
    name: "Front Raise",
    category: "Shoulders",
    equipment: "Dumbbells",
    primaryMuscles: ["Deltoid - Clavicular Part"],
    secondaryMuscles: ["Pectoralis Major - Clavicular Part", "Deltoid - Acromial Part"],
    preparation: "Stand with dumbbells in front of thighs.",
    execution: "Raise one or both up to eye level. Lower with control.",
    tip: "Avoid using momentum. Keep core braced.",
  },
  {
    id: "ex_rear_delt",
    name: "Rear Delt Fly",
    category: "Shoulders",
    equipment: "Dumbbells",
    primaryMuscles: ["Posterior Deltoid"],
    secondaryMuscles: ["Rhomboid Major", "Trapezius - Middle Fibers"],
    preparation: "Hinge forward, chest near parallel, dumbbells hanging.",
    execution: "Open arms wide to shoulder level, squeeze rear delts.",
    tip: "Light weight, high reps. Quality over ego on this one.",
  },
  {
    id: "ex_reverse_pec",
    name: "Reverse Pec Deck",
    category: "Shoulders",
    equipment: "Machine",
    primaryMuscles: ["Posterior Deltoid"],
    secondaryMuscles: ["Rhomboid Major", "Trapezius - Middle Fibers"],
    preparation: "Sit facing the pad, handles in line with shoulders.",
    execution: "Pull arms back and out, squeeze, return slowly.",
    tip: "Great rear delt isolation with no balance needed.",
  },
  {
    id: "ex_upright_row",
    name: "Upright Row",
    category: "Shoulders",
    equipment: "Barbell",
    primaryMuscles: ["Deltoid - Acromial Part", "Trapezius - Upper Fibers"],
    secondaryMuscles: ["Biceps Brachii - Long Head"],
    preparation: "Stand with bar at thighs, slightly wider than shoulder width.",
    execution: "Pull bar up to chest height, elbows leading.",
    tip: "Stop at chest level. Higher pulls can pinch the shoulder.",
  },
  {
    id: "ex_landmine",
    name: "Landmine Press",
    category: "Shoulders",
    equipment: "Barbell",
    primaryMuscles: ["Deltoid - Clavicular Part"],
    secondaryMuscles: ["Serratus Anterior", "Triceps Brachii Lateral", "Pectoralis Major - Clavicular Part"],
    preparation: "Stand staggered stance with one end of barbell at shoulder.",
    execution: "Press up and slightly forward. Reverse to start.",
    tip: "Shoulder-friendly pressing variation.",
  },

  // ============== FULL BODY ==============
  {
    id: "ex_clean",
    name: "Power Clean",
    category: "Full Body",
    equipment: "Barbell",
    primaryMuscles: [
      "Gluteus Maximus",
      "Quadriceps",
      "Erector Spinae",
      "Trapezius - Upper Fibers",
    ],
    secondaryMuscles: [
      "Biceps Femoris",
      "Deltoid - Clavicular Part",
      "Forearm Flexors",
      "Rectus Abdominis",
    ],
    preparation: "Bar over mid foot, hook grip, hips above knees.",
    execution: "Pull explosively, shrug, drop under bar to catch in front rack.",
    tip: "Speed under the bar matters more than how hard you pull.",
  },
  {
    id: "ex_clean_press",
    name: "Clean and Press",
    category: "Full Body",
    equipment: "Barbell",
    primaryMuscles: ["Deltoid - Clavicular Part", "Gluteus Maximus", "Quadriceps"],
    secondaryMuscles: [
      "Erector Spinae",
      "Trapezius - Upper Fibers",
      "Triceps Brachii Lateral",
    ],
    preparation: "Bar on floor in clean setup.",
    execution: "Clean to front rack, then strict press overhead. Lower with control.",
    tip: "Reset your breath at the rack before pressing.",
  },
  {
    id: "ex_thruster",
    name: "Thruster",
    category: "Full Body",
    equipment: "Barbell",
    primaryMuscles: ["Quadriceps", "Deltoid - Clavicular Part", "Gluteus Maximus"],
    secondaryMuscles: ["Triceps Brachii Lateral", "Erector Spinae"],
    preparation: "Front rack, feet shoulder width.",
    execution: "Front squat to depth, then drive up and press bar overhead in one motion.",
    tip: "Use leg drive to start the press.",
  },
  {
    id: "ex_burpee",
    name: "Burpee",
    category: "Full Body",
    equipment: "Bodyweight",
    primaryMuscles: ["Quadriceps", "Pectoralis Major - Sternocostal Part", "Deltoid - Clavicular Part"],
    secondaryMuscles: ["Triceps Brachii Lateral", "Rectus Abdominis", "Gluteus Maximus"],
    preparation: "Stand with feet hip width.",
    execution: "Drop to plank, push up, hop feet in, jump up reaching overhead.",
    tip: "Pace yourself. Burpees punish poor pacing.",
  },
  {
    id: "ex_kb_swing",
    name: "Kettlebell Swing",
    category: "Full Body",
    equipment: "Kettlebell",
    primaryMuscles: ["Gluteus Maximus", "Biceps Femoris", "Erector Spinae"],
    secondaryMuscles: ["Latissimus Dorsi", "Deltoid - Clavicular Part", "Rectus Abdominis"],
    preparation: "Stand, KB between feet, hinge to grab handle.",
    execution: "Hike back, snap hips forward, let bell float to chest height.",
    tip: "It's a hip hinge, not a squat. Don't 'lift' with the arms.",
  },
  {
    id: "ex_turkish",
    name: "Turkish Get Up",
    category: "Full Body",
    equipment: "Kettlebell",
    primaryMuscles: ["Deltoid - Clavicular Part", "Gluteus Maximus", "Rectus Abdominis"],
    secondaryMuscles: ["Triceps Brachii Lateral", "Quadriceps", "Erector Spinae", "Trapezius - Middle Fibers"],
    preparation: "Lie on back, KB pressed up with one arm.",
    execution: "Stand up keeping KB locked overhead, then reverse to the floor.",
    tip: "Move slow. Your eyes should stay on the bell the whole time.",
  },
  {
    id: "ex_farmer",
    name: "Farmer Carry",
    category: "Full Body",
    equipment: "Dumbbells",
    primaryMuscles: ["Forearm Flexors", "Trapezius - Upper Fibers", "Rectus Abdominis"],
    secondaryMuscles: ["Quadriceps", "Gluteus Maximus", "Erector Spinae"],
    preparation: "Pick up two heavy dumbbells, stand tall.",
    execution: "Walk for distance or time. Stay upright, ribs down.",
    tip: "Brutal grip and core work. Don't sandbag the weight.",
  },
  {
    id: "ex_renegade",
    name: "Renegade Row",
    category: "Full Body",
    equipment: "Dumbbells",
    primaryMuscles: ["Latissimus Dorsi", "Rhomboid Major", "Rectus Abdominis"],
    secondaryMuscles: ["Pectoralis Major - Sternocostal Part", "Triceps Brachii Lateral"],
    preparation: "Plank with hands on dumbbells, feet wide.",
    execution: "Row one dumbbell to hip while bracing. Alternate sides.",
    tip: "Anti-rotation work. Keep the hips dead level.",
  },

  // ============== PERSONAL GYM MACHINES ==============
  {
    id: "ex_hammer_inc",
    name: "Hammer Strength Incline Press",
    category: "Chest",
    equipment: "Plate-Loaded Machine",
    primaryMuscles: ["Pectoralis Major - Clavicular Part"],
    secondaryMuscles: [
      "Deltoid - Clavicular Part",
      "Triceps Brachii Lateral",
      "Triceps Brachii Longus",
    ],
    preparation: "Set seat so handles align with mid-upper chest. Plant feet, retract scapulae.",
    execution: "Press handles forward and slightly up. Control the eccentric to a deep stretch.",
    tip: "Build up: 45 -> 55 -> 65 lb each side. Independent arms expose any side dominance.",
  },
  {
    id: "ex_hammer_supine",
    name: "Hammer Strength Supine Press",
    category: "Chest",
    equipment: "Plate-Loaded Machine",
    primaryMuscles: ["Pectoralis Major - Sternocostal Part"],
    secondaryMuscles: [
      "Triceps Brachii Lateral",
      "Triceps Brachii Longus",
      "Deltoid - Clavicular Part",
    ],
    preparation: "Lie back with handles aligned to mid chest. Feet flat, scapulae pinned.",
    execution: "Press handles up and slightly together. Lower with full control.",
    tip: "Build up: 55 -> 65 -> 70 lb each side. Match the rep cadence to the incline machine.",
  },
  {
    id: "ex_foreman_231",
    name: "Foreman FLY-231 Chest Fly",
    category: "Chest",
    equipment: "Plate-Loaded Machine",
    primaryMuscles: ["Pectoralis Major - Sternocostal Part", "Pectoralis Major - Clavicular Part"],
    secondaryMuscles: ["Deltoid - Clavicular Part", "Biceps Brachii - Short Head"],
    preparation: "Set seat so handles line up with mid chest. Soft elbow bend.",
    execution: "Bring handles together in front of the chest, squeeze, return slowly to deep stretch.",
    tip: "Open at 25 lb each side next session. PR is 35 lb x 7 — chase a clean 8.",
  },
  {
    id: "ex_db_pullover",
    name: "Dumbbell Pullover",
    category: "Chest",
    equipment: "Dumbbells",
    primaryMuscles: ["Pectoralis Major - Sternocostal Part", "Latissimus Dorsi"],
    secondaryMuscles: ["Triceps Brachii Longus", "Serratus Anterior"],
    preparation: "Lie across or along a bench. Hold one dumbbell with both hands above the chest.",
    execution: "Lower the dumbbell back overhead in an arc. Pull it back over the chest.",
    tip: "Permanent staple. Slow stretch at the bottom. Ribs stay down — don't flare.",
  },
  {
    id: "ex_lat_pull_reverse",
    name: "Reverse Grip Lat Pulldown",
    category: "Back",
    equipment: "Cable",
    primaryMuscles: ["Latissimus Dorsi", "Biceps Brachii - Long Head"],
    secondaryMuscles: ["Trapezius - Lower Fibers", "Posterior Deltoid"],
    preparation: "Underhand grip just inside shoulder width. Sit tall, knees secured.",
    execution: "Pull bar to upper chest, drive elbows down and back. Slow eccentric.",
    tip: "Superset partner to wide-grip pulldown — same weight, no rest in between.",
  },
  {
    id: "ex_machine_lat_raise",
    name: "Machine Lateral Raise",
    category: "Shoulders",
    equipment: "Machine",
    primaryMuscles: ["Deltoid - Acromial Part"],
    secondaryMuscles: ["Trapezius - Upper Fibers"],
    preparation: "Adjust seat so pads sit just above the elbows. Grip handles loosely.",
    execution: "Drive elbows out and up to shoulder height. Pause briefly, lower under control.",
    tip: "Stop at shoulder height. Anything higher is just trap recruitment.",
  },
  {
    id: "ex_db_shrug",
    name: "Dumbbell Shrugs",
    category: "Shoulders",
    equipment: "Dumbbells",
    primaryMuscles: ["Trapezius - Upper Fibers"],
    secondaryMuscles: ["Levator Scapulae"],
    preparation: "Stand tall with a dumbbell in each hand at the sides.",
    execution: "Shrug straight up toward the ears. Hold, lower with control. No rolling.",
    tip: "All 3 working sets at the same weight. Quality reps over heaviest reps.",
  },
  {
    id: "ex_foreman_217_low",
    name: "Foreman FLY-217 Low Row Rear Delt",
    category: "Shoulders",
    equipment: "Plate-Loaded Machine",
    primaryMuscles: ["Posterior Deltoid"],
    secondaryMuscles: ["Trapezius - Middle Fibers", "Rhomboid Major"],
    preparation: "Set up at the low row station. Grip handles, slight forward lean.",
    execution: "Pull elbows wide and back to bias the rear delts. Squeeze, return slow.",
    tip: "Light weight, strict form. Rear delts respond to volume not load.",
  },
  {
    id: "ex_cable_curl",
    name: "Cable Curl",
    category: "Arms",
    equipment: "Cable",
    primaryMuscles: ["Biceps Brachii - Short Head", "Biceps Brachii - Long Head"],
    secondaryMuscles: ["Brachialis", "Brachioradialis"],
    preparation: "Cable in low position. Straight or EZ bar attached. Stand close to the stack.",
    execution: "Curl the bar up while keeping elbows pinned. Squeeze, lower under control.",
    tip: "7th pin from the top on the AMP cable stack = 32.5 lb. PR pin one heavier.",
  },
  {
    id: "ex_cable_overhead_tri",
    name: "Cable Overhead Triceps Extension",
    category: "Arms",
    equipment: "Cable",
    primaryMuscles: ["Triceps Brachii Longus"],
    secondaryMuscles: ["Triceps Brachii Lateral", "Triceps Brachii Medial"],
    preparation: "Rope on high pulley. Face away from the cable, split stance, lean forward slightly.",
    execution: "Press the rope forward and up overhead until elbows lock. Slow stretch back.",
    tip: "Face away from the cable — that's the cue that opens up the long head.",
  },
  {
    id: "ex_db_curl_blaster",
    name: "DB Curl (Arm Blaster)",
    category: "Arms",
    equipment: "Dumbbells",
    primaryMuscles: ["Biceps Brachii - Short Head", "Biceps Brachii - Long Head"],
    secondaryMuscles: ["Brachialis"],
    preparation: "Strap on the arm blaster. Elbows locked against the pad, dumbbells at sides.",
    execution: "Curl one arm at a time. Strict — no swinging, no elbow drift.",
    tip: "Wednesday staple. The blaster removes any cheat — pure biceps.",
  },
  {
    id: "ex_hip_adductor",
    name: "Hip Adductor",
    category: "Legs",
    equipment: "Machine",
    primaryMuscles: ["Adductor Magnus", "Adductor Longus", "Adductor Brevis"],
    secondaryMuscles: ["Pectineus", "Gracilis"],
    preparation: "Sit upright, knees bent, inner thighs against the pads.",
    execution: "Squeeze knees together against pads, hold, return slowly to stretch.",
    tip: "Pair with the abductor every legs day. Inner thigh balance keeps the squat honest.",
  },
];
