uploads = []
outputs = []

[[generated]]
id = "V-doz2HgMM424Ar5qRnKJ"
uri = "file://artifacts/gym-log/public/icon.png"
type = "image"
title = "LiftIQ"

[[generated]]
id = "LLeiYC7Ajnmcu6btAEstP"
uri = "file://artifacts/gym-log/assets/images/icon.png"
type = "image"
title = "LiftIQ app icon"
